### ISSUE TITLE
Cortex should start with empty values in cortex_conf.env, but disable features that are insufficiently configured.

### ISSUE THREAD

**Issue by awilson-cloudpassage** [cloudpassage/cortex#39]
Expected behavior:
If any field prefixed by `QUARANTINE` is empty, the quarantine feature will be disabled.
If any field prefixed by `IPBLOCKER` is empty, IP blocker will be disabled.

If `SUPPRESS_EVENTS_IN_CHANNEL` is empty, no events will be suppressed.  Otherwise, the contents of this field will be treated as a comma-delimited string of event types that should not be placed in-channel by donbot.

**Comment by awilson-cloudpassage** [comment]
@eatwithforks 👀

**Comment by eatwithforks** [comment]
if fields are not empty, validate the values are the correct class types.

**Comment by ashmastaflash** [comment]
@eatwithforks I need some clarification.  Unlike .yaml or json files, the dotenv only ever gives you strings (via environment variables).  If you're looking for object validation, (group is, server id, etc) that happens in the Python SDK as a measure for preventing path traversal (see https://github.com/cloudpassage/cloudpassage-halo-python-sdk/blob/master/cloudpassage/sanity.py#L8).  

Are you looking for assertion of the unambiguous existence of a named object (like server group) against the API, as a matter of config file validation?  Or is there something else you're looking for?

**Comment by eatwithforks** [comment]
The environment variables for everything in cortex_conf should undergo class type validation. Check out https://github.com/cloudpassage/don-bot/blob/master/app/cortexlib/config_helper.py. It already does it for most of them except in the case when IPBLOCKER_ENABLED and QUARANTINE_ENABLED is None. Which is the main task for this issue. When those two variables are filled, they should be validate as boolean.
